---
title: "Supplemental Figure 8 - Species relative abundance"
output: html_notebook
---

```{r setup, include=FALSE}
library(tidyverse)
library(reshape2)
library(scales)

dat <- read_csv("./data/species table.csv") %>% column_to_rownames("SampleID")
metadata <- read_csv("./data/clinical attributes comut.csv") %>% column_to_rownames("casenum")
                     
bar_colors <- c("#3288BD", "#5E4FA2", "#66A61E", "#FFED6F", "#FF0000", "#F46D43", 
                         "#E7298A", "#00008B", "#8DD3C7", "#FFFFB3", "#BEBADA", "#FB8072", 
                         "#80B1D3", "#B3DE69", "#FCCDE5", "#BC80BD", "#CCEBC5", "#9E0142",
                         "#D53E4F", "#FDAE61", "#FEE08B", "#333333", "#66C2A5", "#3288BD",
                         "#1B9E77", "#D95F02", "#7570B3", "#E6AB02", "#A6761D")
```

``` {r plot}
num_top <- 20
bar_colors <- bar_colors[1:num_top]
bar_colors <- c(bar_colors, "#808080")  # add grey for "Other"

top_names <- names(sort(rowMeans(dat), decreasing=TRUE))[1:num_top]
top_features <- dat[top_names, ]

# add in "other" taxa as a column for display
top_features["Other", ] <- 1 - colSums(top_features)
top_features["Other", ][top_features["Other", ] < 0] <- 0  # can occasionally end up with small negative values for some reason

# melt
top_features$feature <- row.names(top_features)
top_features <- melt(top_features, id.vars = "feature")
top_features$feature <- factor(top_features$feature, ordered = TRUE, levels = c(top_names, "Other"))

# add metadata
top_features <- bind_cols(top_features, metadata[match(top_features$variable, row.names(metadata)), ])
top_features$responder <- ifelse(top_features$bestresp == "PR", "Response", "No response")
top_features$responder <- factor(top_features$responder, levels = c("Response", "No response"))
top_features$variable <- factor(top_features$variable, levels = sort(as.numeric(levels(top_features$variable))))

p <- ggplot(top_features, aes(variable, fill = feature)) + 
  geom_bar(aes(weight = value), position = position_fill(reverse = TRUE)) + 
  theme_bw(base_size = 12) + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + 
  xlab("Case Number") + ylab("Relative Abundance") + theme(legend.text = element_text(face = "italic", size = 10)) +
  guides(title="Species", fill = guide_legend(ncol = 1, keyheight = 0.55, reverse = TRUE)) + 
  scale_y_continuous(labels = label_percent(), expand = expansion(mult = c(0.01, 0.01))) + 
  scale_fill_manual(values = bar_colors) +
  facet_grid(~responder, scales = "free", space = "free_x")
p
ggsave("./NIMBUS Figures/Supplemental Figure 8.pdf", width = 12, height = 7)
```
